# Generated by Django 2.2.7 on 2019-11-19 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LineItem',
            new_name='Transaction',
        ),
    ]
