# Generated by Django 4.2.6 on 2023-10-14 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0002_auto_20191119_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('budget', models.FloatField()),
                ('actuals', models.FloatField()),
                ('eac', models.FloatField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('transactions', models.ManyToManyField(to='Transactions.transaction')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Transactions.category'),
            preserve_default=False,
        ),
    ]
