# Generated by Django 4.2.6 on 2023-10-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0005_budget_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='category',
        ),
        migrations.AddField(
            model_name='budget',
            name='currency',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
